# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: hashi_vault
version: 1.4.0
readme: README.md
authors:
  - Jonathan Davila
  - Brian Scholer (@briantist)
description: Plugins related to HashiCorp Vault
license_file: LICENSE
tags:
  # tags so people can search for collections https://galaxy.ansible.com/search
  # tags are all lower-case, no spaces, no dashes.
  - vault
  - hashicorp
  - secret
  - secrets
  - password
  - passwords
repository: https://github.com/ansible-collections/community.hashi_vault
documentation: https://docs.ansible.com/ansible/devel/collections/community/hashi_vault
homepage: https://github.com/ansible-collections/community.hashi_vault
issues: https://github.com/ansible-collections/community.hashi_vault/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
