---
name: Calculate diff output between two Ansible docs builds
description: Compare two builds of docs (HTML files) and produce diff output.
inputs:
  build-html-a:
    description: The path to the HTML files (set A).
    required: true
  build-html-b:
    description: The path to the HTML files (set B).
    required: true
  diff-size-limit:
    description: The maximum size of the diff output. Larger output will be truncated.
    required: false
    default: '60000'

outputs:
  diff:
    description: The diff text.
    value: ${{ steps.diff.outputs.diff }}
  truncated:
    description: Will be 'true' if the output was truncated, otherwise 'false'.
    value: ${{ steps.diff.outputs.truncated }}
  files-raw:
    description: The unmodified diff file list output.
    value: ${{ steps.diff.outputs.files-raw }}
  files-trimmed:
    description: The diff output with paths trimmed to be relative to the doc root
    value: ${{ steps.diff.outputs.files-trimmed }}
runs:
  using: composite
  steps:
    - name: Prepare vars
      id: diff
      uses: actions/github-script@v5
      with:
        script: |
          // attribution: https://stackoverflow.com/a/3561711/3905079
          function escapeRegex(string) {
              return string.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
          }

          const inputs = ${{ toJSON(inputs) }}

          const pathA = inputs['build-html-a']
          const pathB = inputs['build-html-b']
          const maxLen = Number(inputs['diff-size-limit'])

          const regEscPathA = escapeRegex(pathA)
          const regEscPathB = escapeRegex(pathB)

          const regPathSearcher = new RegExp(`^([A-Z])\\s+(${regEscPathA}|${regEscPathB})\\/(.*?)$`, 'gm')
          const regPathReplacer = '$1 $3'

          const fileListOpts = {
              ignoreReturnCode: true, // git diff sets return code to 1 when there are differences
              listeners: {
                  stdout: (data) => {
                      fileListRaw = data.toString()
                      fileListTrimmed = fileListRaw.replace(regPathSearcher, regPathReplacer)

                      core.setOutput('files-raw', fileListRaw)
                      core.setOutput('files-trimmed', fileListTrimmed)
                  }
              }
          }
          const diffOpts = {
              ignoreReturnCode: true, // git diff sets return code to 1 when there are differences
              listeners: {
                  stdout: (data) => {
                      diff = data.toString()
                      truncated = false
                      if (diff.length > maxLen) {
                          core.information(`Diff output exceeded ${maxLen} and will be truncated.`)
                          diff = diff.substring(0, maxLen)
                          truncated = true
                      }

                      core.setOutput('truncated', truncated)
                      core.setOutput('diff', diff)
                  }
              }
          }

          // start the process to get the diff text
          const getDiffOutput = exec.exec('git', [
              '--no-pager', 'diff', '--histogram', '--no-index',
              '--relative', '--diff-filter=ad', pathA, pathB
          ], diffOpts)

          // start the process to get the diff file list
          const getFileList = exec.exec('git', [
              '--no-pager', 'diff', '--name-status', '--no-index',
              '--relative', pathA, pathB
          ], fileListOpts)

          await Promise.all([getFileList, getDiffOutput])
