---
name: Install Docker on MacOS GitHub Runner
description: Install and configure docker for a MacOS GitHub runner, and export the environment variables.
branding:
  icon: command
  color: white
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p ~/.docker/machine/cache
        curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
        brew install docker-machine docker
        docker --version
        docker-machine create --driver virtualbox default
        docker-machine env default
        docker-machine env default | sed 's/^export //;/^#/d;s/^#.*//' | tr -d '"' >> $GITHUB_ENV
