---
name: Ansible docs build
on:
  workflow_call:
    inputs:
      collections:
        required: false
        type: string
      python:
        required: false
        type: string

    # outputs:

jobs:
  build-ansible-docs:
    name: Build Ansible Docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        if: inputs.python != ''
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python }}

      - name: Initialize the build environment
        uses: ./.github/actions/docs/ansible-docs-build-init
        with:
          collections: ${{ inputs.collections }}
