---
name: Ansible docs build
on:
  workflow_call:
    inputs:
      collections:
        required: false
        type: string
      python:
        required: false
        type: string
        default: '3.9'
      ansible-ref:
        required: false
        type: string
        default: milestone

    # outputs:

jobs:
  build-ansible-docs:
    name: Build Ansible Docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up Python
        if: inputs.python != ''
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python }}

      - name: Install Ansible
        run: pip install https://github.com/ansible/ansible/archive/${{ inputs.ansible-ref }}.tar.gz --disable-pip-version-check

      - name: Initialize the build environment
        id: init
        uses: ansible-collections/community.hashi_vault/.github/actions/docs/ansible-docs-build-init@docs/build-v2
        with:
          collections: ${{ inputs.collections }}

      - name: Checkout test
        # if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ansible_collections/${{ inputs.collection }}

      - name: Build test
        env:
          ANSIBLE_COLLECTIONS_PATHS: ansible_collections/${{ inputs.collection }}
        run: ${{ steps.init.outputs.build-script }}
